#include "globalsymbols.h"
//---------------------------------------------------------------------------
#include "bodypart.h"
#include "movecmd.h"
#define MAXTOKEN 250

static TOKENELEMENT  baseTokens[ MAXTOKEN ]={
	{"NOTOKEN",  NoToken,nocmd},
	{"LET",      SysCmd,Let},
	{"DEFPROC",  SysCmd,defProc},
	{"BLOCK",    SysCmd,doProc},
	{"UNDEF",    SysCmd,unDef},
	{"LOCKPOS",  VoidCmd,lockposcmd},
	{"UNLOCKPOS",VoidCmd,unlockposcmd},
	{"MIRROR",   ProcFlag,mirrorcmd},
	{"LEFT",     ProcFlag,mirrorcmd},
	{"RIGHT",    ProcFlag,nocmd},
	{"STARTTIME",IntCmd,starttimecmd},
	{"DELTATIME",IntCmd,deltaTimecmd},
	{"TIME",     IntCmd,timecmd},
	{"DT",       IntCmd,deltaTimecmd},
	{"T",        IntCmd,timecmd},
	{"BODYLOC",  XYZBodyCmd,BODYLOCATION},
	{"BODYLOCATION",XYZBodyCmd,BODYLOCATION},
	{"BODYTURN", VHRBodyCmd,BODYTURN},
	{"PELVISLOC",XYZBodyCmd,PELVISLOC},
	{"PELVIS",   VHRBodyCmd,PELVIS},
	{"WAIST",    VHRBodyCmd,WAIST},
	{"UPPERBACK",VHRBodyCmd,UPPERBACK},
	{"CHEST",    VHRBodyCmd,UPPERBACK},
	{"HEAD",     VHRBodyCmd,HEAD},
	{"NECK",     VHRBodyCmd,NECK},
	{"RARM",     VHRBodyCmd,RARM},
	{"RSHOULDER",VHRBodyCmd,RSHOULDER},
	{"RELBOW",   VHRBodyCmd,RELBOW},
	{"RWRIST",   VHRBodyCmd,RWRIST},
	{"RHAND",    VHRBodyCmd,RWRIST},
	{"RFINGERS", VHRBodyCmd,RFINGERS},
	{"RTHUMB",   VHRBodyCmd,RTHUMB},
	{"LARM",     VHRBodyCmd,LARM},
	{"LSHOULDER",VHRBodyCmd,LSHOULDER},
	{"LELBOW",   VHRBodyCmd,LELBOW},
	{"LWRIST",   VHRBodyCmd,LWRIST},
	{"LHAND",    VHRBodyCmd,LWRIST},
	{"LFINGERS", VHRBodyCmd,LFINGERS},
	{"LTHUMB",   VHRBodyCmd,LTHUMB},
        {"RHIP",     VHRBodyCmd,RHIP},
	{"RLEG",     VHRBodyCmd,RHIP},
	{"RKNEE",    VHRBodyCmd,RKNEE},
	{"RANKLE",   VHRBodyCmd,RANKLE},
	{"RFOOT",    VHRBodyCmd,RANKLE},
	{"RTOES",    VHRBodyCmd,RTOE},
	{"LHIP",     VHRBodyCmd,LHIP},
	{"LLEG",     VHRBodyCmd,LHIP},
	{"LKNEE",    VHRBodyCmd,LKNEE},
	{"LANKLE",   VHRBodyCmd,LANKLE},
	{"LFOOT",    VHRBodyCmd,LANKLE},
	{"LTOES",    VHRBodyCmd,LTOE},
	{"VERT",     IntCmd,vertangle},
	{"HOR",      IntCmd,horangle},
	{"ROT",      IntCmd,rotangle},
	{"V",        IntCmd,vertangle},
	{"H",        IntCmd,horangle},
	{"R",        IntCmd,rotangle},
	{"DELTAV",   IntCmd,dvertangle},
	{"DELTAH",   IntCmd,dhorangle},
	{"DELTAR",   IntCmd,drotangle},
	{"DV",       IntCmd,dvertangle},
	{"DH",       IntCmd,dhorangle},
	{"DR",       IntCmd,drotangle},
	{"X",        IntCmd,xpos},
	{"Y",        IntCmd,ypos},
	{"Z",        IntCmd,zpos},
	{"DELTAX",   IntCmd,dxpos},
	{"DELTAY",   IntCmd,dypos},
	{"DELTAZ",   IntCmd,dzpos},
	{"DX",       IntCmd,dxpos},
	{"DY",       IntCmd,dypos},
	{"DZ",       IntCmd,dzpos},
	{"RX",       IntCmd,rxpos},
	{"RZ",       IntCmd,rzpos},
	{"DUR",      IntCmd,duration},
	{"D",        IntCmd,duration},
	{";",        Comment,0},
	{"",         NoToken,0}
};


TokenList gSymboltable(baseTokens);

